import Navbar from "@/lib/modules/layout/navbar";
import NavbarResolver from "@/lib/modules/layout/navbar-resolver";
import { body } from "@/utils/fonts";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${body.className} antialiased`}>
				<NavbarResolver />
				<Navbar />
				{children}
			</body>
		</html>
	);
}
